name: De Systeembeheerder
favicon: null
layout_spectrum: 0.25346
typography_spectrum: 0.55124
title: Wij zorgen dat ICT werkt. Altijd. Overal.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00ca34'
    - '#ffffff'
    - '#2f2f2f'
    - '#70e18d'
    - '#909090'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
